quant_stage:
  quant_modifiers:
    QuantizationModifier:
      ignore: [lm_head]
      config_groups:
        group_0:
          weights: 
            num_bits: 8
            type: int
            symmetric: true
            strategy: group
            group_size: 128
          activations: 
            num_bits: 16
            type: float
          targets: [Linear]